### ISSUE TITLE
so what does this fix?

### ISSUE THREAD

**Issue by brandyyn** [LITW-Refined/plantmegapackfix#2]
this has literally no info

**Comment by Pilzinsel64** [comment]
... because I never came to yet. Always wanted to complete Readmes for all my minor mods and make a minor post on Discord but never did yet. Still to be done.

This mod fixes a worldgen bug that usually leads to a server crash when you explore the world. There were a minor mistake maken in Plant Mega Pack for one kind of plants (happens). I'm open to accept PRs for more fixes whenever new have been found or whenever I came to fix some.

**Comment by brandyyn** [comment]
> ... because I never came to yet. Always wanted to complete Readmes for all my minor mods and make a minor post on Discord but never did yet. Still to be done.
> 
> This mod fixes a worldgen bug that usually leads to a server crash when you explore the world. There were a minor mistake maken in Plant Mega Pack for one kind of (happens).

Can you elaborate on the crash? I use PlantMegaPack in my modpack and I do sometimes get a world gen crash but I wasn’t aware it was from PlantMegaPack, if you could give some more specifics that would be great 🥺 if it does fix the bug that would be awesome! But I’m hesitant to try something that has no documentation and a bug report 😭 but I really appreciate the work.

**Comment by Pilzinsel64** [comment]
I'm not entirely sure if there was a good crash report. As far as I know it started to get in a loop until the server decides to crash. I had to check that via an analytics tool and it took me a long while until I got the reason. The method `genVine()` in `PMPGenVine` in Plant Mega Pack never checks the actual `y` value like all the other `gen...()` methods in other gen classes. The method starts at 255 (max height) and goes down block for block and checks if a vine would be cool to spawn here. If not the values will reach 0 after some time. At this point the method should break and accept that it will not be able to spawn a vine at this x/z position and return. But in PMP it never does. This Mixin fixes it and because I'm bad in replacing single conditions I replaced the whole method via injection.

See the line here:
https://github.com/LITW-Refined/plantmegapackfix/blob/6853374569aa496060f206282ca430647451610b/src/main/java/de/pilz/plantmegapackfix/mixins/PMPGenVineMixin.java#L35
The `y > 1` was missing here in PlantMegaPack itself, that's why the world gen loop with server crash and the mixin here.

**Comment by brandyyn** [comment]
> I'm not entirely sure if there was a good crash report. As far as I know it started to get in a loop until the server decides to crash. I had to check that via an analytics tool and it took me a long while until I got the reason. The method `genVine()` in `PMPGenVine` in Plant Mega Pack never checks the actual `y` value like all the other `gen...()` methods in other gen classes. The method starts at 255 (max height) and goes down block for block and checks if a vine would be cool to spawn here. If not the values will reach 0 after some time. At this point the method should break and accept that it will not be able to spawn a vine at this x/z position and return. But in PMP it never does. This Mixin fixes it and because I'm bad in replacing single conditions I replaced the whole method via injection.
> 
> See the line here:
> 
> https://github.com/LITW-Refined/plantmegapackfix/blob/6853374569aa496060f206282ca430647451610b/src/main/java/de/pilz/plantmegapackfix/mixins/PMPGenVineMixin.java#L35
> 
> 
> The `y > 1` was missing here in PlantMegaPack itself, that's why the world gen loop with server crash and the mixin here.

I will try the fork, I was told it needs to be run alongside the original plant mega pack? 

Is the other issue report going to be fixed too? 🥺

**Comment by Pilzinsel64** [comment]
> I was told it needs to be run alongside the original plant mega pack?

Of course. I mean, editing the decompiled source of PMP would be also an option but not backward-compatible. That's why an additional minor mixin mod. However, I'll try to move this mixin to BugTourch some day if jss accepts it.

> Is the other issue report going to be fixed too? 🥺

When I get some more free time next year. 🙈 However, PRs are welcome anyway. 😊
